baseurl = "./"
languageCode = "en-us"
title = "ggvisualizer"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-49237071-1"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "ggvisualizer"
    subtitle = "Iteratively understand how a ggplot is created"
    author = "Devin Pastoor"
    
    # Body background color
	bodybgcolor = "#f9f9f9"
    
    # Preview container button text
    buttontext = "See how it's made"
    
    # Footer text
    footertext = "Made by [Devin Pastoor](https://github.com/dpastoor)"
